job: 
  stage: test
  script:
    - oc login -u admin -p redhat1 https://swdvos001.swimtest1.act.faa.gov 
    - oc new-project ncr || oc project ncr
    - oc create -f ncr-operator_deve2.yaml
    - oc apply -f ncr_deve2.yaml
  tags:
    - oc

