---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dvt
  labels:
    app: dvt
  namespace: ncr-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dvt
        name: dvt
    spec:
      serviceAccountName: ncr
      containers:
        - name: dvt
          image: devencrrepo01.ncr.nas.faa.gov:5000/dvt:5.4.6.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /NCRWeb
              port: 8080
              httpHeaders:
                - name: Authorization
                  value: Basic dG9tY2F0OnRvbWNhdA==
          env:
            - name: GATEWAY_HOST
              value: "subscription-service-ncr.deve.ncr.nas.faa.gov"
            - name: DVT_HOST
              value: "dvt-ncr-test.deve.ncr.nas.faa.gov"
            - name: GATEWAY_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dvt
  name: dvt
  namespace: ncr-test
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dvt
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: dvt
  name: dvt
  namespace: ncr-test
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: dvt

