apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: ncr-cluster
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.2"
      log.retention.ms: 1800000
      log.retention.check.internal.ms: 300000
      log.segment.bytes: 536870912
      log.roll.hours: 1
    storage:
      type: persistent-claim 
      size: 5Gi
      class: glusterfs-storage-block
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 2Gi
      class: glusterfs-storage-block
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

